### ISSUE TITLE
Swift 3 지원 요청

### ISSUE THREAD

**Issue by chanoo** [jinSasaki/AlertBar#12]
스위프트 3 지원해주세요.

**Comment by jinSasaki** [comment]
@chanoo 
AlertBar 0.2.0 supported Swift 3.
Please note that CocoaPods 1.1.0(Now [1.1.0.rc.2](https://rubygems.org/gems/cocoapods/versions/1.1.0.rc.2)) is required to install AlertBar 0.2.0.

**Comment by chanoo** [comment]
Thank you!!! 
very very~
