### ISSUE TITLE
Orientation Issue

### ISSUE THREAD

**Issue by gowthamcloridaa** [jinSasaki/AlertBar#26]
Alert bar appears from the left side in the left landscape orientation in iPad's without dropping down from the top.In right landscape orientation, Alert appears appears from the right side with a distance of around 100 points from the corner instead of dropping down from the top

**Comment by jinSasaki** [comment]
It seems that there is no problem with the sample application.
Could you send me the sample code or project to reproduce the issue?

![image](https://user-images.githubusercontent.com/4962215/33539652-dfd0024e-d90a-11e7-9878-9e79ff6e4666.png)

**Comment by jinSasaki** [comment]
I cannot reproduce this issue. I think the issue has been resolved.
If you have any questions, please create a new issue. Thank you! 😄

**Comment by jinSasaki** [comment]
@gowthamcloridaa 
I fixed this issue. Please use `AlertBar 0.4.2`.
Thank you! 😄

**Comment by FaridClorida** [comment]
@jinSasaki Again the same issue is present.

**Comment by jinSasaki** [comment]
@FaridClorida 
Which version do you use?
Could you send me the sample code or project to reproduce the issue?

**Comment by FaridClorida** [comment]
@jinSasaki I had manually integrated the file AlertBar.swift from the project yesterday.

**Comment by FaridClorida** [comment]
@jinSasaki The issue is still present in iPad

**Comment by FaridClorida** [comment]
![simulator screen shot - ipad pro 10 5-inch - 2018-06-20 at 11 10 44](https://user-images.githubusercontent.com/31611072/41639406-43ad87c6-747b-11e8-9953-fb4b6c312aa6.png)
