### ISSUE TITLE
Complier Error

### ISSUE THREAD

**Issue by russelltwarwick** [jinSasaki/AlertBar#32]
Error within the alert bar for func handleRotate()

> dynamic' instance method 'handleRotate' must also be '@objc

**Comment by jinSasaki** [comment]
@waruss321 
Which version do you use?
It is already fixed in 0.3.3 or later.

**Comment by russelltwarwick** [comment]
Might be an issue with the pod file I used

**Comment by jinSasaki** [comment]
I think this issue is already resolved because of no reply.
If you find the same issue, please create a new one.
Thanks :)
