### ISSUE TITLE
Orientation issue is still present 

### ISSUE THREAD

**Issue by abcross92** [jinSasaki/AlertBar#34]
iPad Pro 9.7
iOs 11.2.5
I created a fix for it. Apologies I am new to github and don't know if there is a way for me to create a PR
<img width="1512" alt="screen shot 2018-02-08 at 3 11 30 pm" src="https://user-images.githubusercontent.com/11010082/35998486-675ad38c-0ce2-11e8-8c07-85f934a66afa.png">

**Comment by jinSasaki** [comment]
@abcross92 
Thanks for creating issue!
I checked that issue on iOS Simulator, using AlertBar 0.4.2 via CocoaPods, but it does not reproduce.

Could you tell me your environment?
A sample project the issue reproduce helps me fix it, so please send the project if you can. :)

```swift
import UIKit
import AlertBar

class ViewController: UIViewController {
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        AlertBar.show(type: .notice, message: "this is sample message")
    }
}
```

![image](https://user-images.githubusercontent.com/4962215/36007347-6936080e-0d85-11e8-9d70-10bcbe0ef9e1.png)

**Comment by abcross92** [comment]
Hmm, I am having trouble reproducing it outside of the app I am working on unfortuanately.
I am seeing this issue on a physical device (unfortunately we are having some issues that prevent us from running on the sim right now)

We have an app with a UIPageViewController.All screens are designed with VIPER architecture.
We set these settings in the AppDelegate
```Swift
AlertBar.shared
            .setDefault(options: AlertBar.Options(shouldConsiderSafeArea: true,
                                                  isStretchable: true,
                                                  textAlignment: .center))
```

And one example of us calling the show method
```Swift
AlertBar.shared.show(type: .success,
                                 message: "this was a method call",
                                 duration: 4)
```

**Comment by jinSasaki** [comment]
@abcross92 
This issue did not reproduce on the real device (iPad Pro 9.7). ;(
Does your app have the implementation related to UIWindow or something window hierarchy?
I think it is related to this issue.

If the sample project reproduces the issue, I will fix soon!

**Comment by jinSasaki** [comment]
I think this issue is already resolved because of no reply.
If you find the same issue, please create a new one.
Thanks :)

**Comment by abcross92** [comment]
O sorry for no reply. 

It was faster for me to just rewrite AlertBar myself than try to prove the issue
